service: employee-crud-api

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-south-1
  environment:
    DYNAMODB_TABLE_NAME: ${self:custom.employeeTableName}

custom:
  employeeTableName: employee-table-${self:provider.stage}

plugins:
  - serverless-iam-roles-per-function
functions:
  getEmployee:
    handler: app.getEmployee
    name: get-employee
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: employee/{employeeId}
          method: GET
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:GetItem"
        Resource: !GetAtt EmployeeTable.Arn
        
  createEmployee:
    handler: app.createEmployee
    name: create-employee
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: employee
          method: POST
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:PutItem"
        Resource: !GetAtt EmployeeTable.Arn

  updateEmployee:
    handler: app.updateEmployee
    name: update-employee
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: employee/{employeeId}
          method: PUT
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:UpdateItem"
        Resource: !GetAtt EmployeeTable.Arn

  deleteEmployee:
    handler: app.deleteemployee
    name: delete-employee
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: employee/{employeeId}
          method: DELETE
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:DeleteItem"
        Resource: !GetAtt EmployeeTable.Arn

  getAllEmployees:
    handler: app.getAllemployees
    name: get-all-employees
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: employees
          method: GET
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:Scan"
        Resource: !GetAtt EmployeeTable.Arn

resources:
  Resources:
    EmployeeTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.employeeTableName}
        AttributeDefinitions:
          - AttributeName: employeeId
            AttributeType: S
        KeySchema:
          - AttributeName: employeeId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1